
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: D:/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.44.35217 版
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.44.35217.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/Estim/Desktop/lin/cmake_code/src/101_first_cmake/nmake/CMakeFiles/3.27.0/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1158 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        注意: 包含文件:  C:\\Users\\Estim\\Desktop\\lin\\cmake_code\\src\\101_first_cmake\\nmake\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "注意: 包含文件:  "
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: D:/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.44.35217 版
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.44.35217.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/Estim/Desktop/lin/cmake_code/src/101_first_cmake/nmake/CMakeFiles/3.27.0/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1158 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        注意: 包含文件:  C:\\Users\\Estim\\Desktop\\lin\\cmake_code\\src\\101_first_cmake\\nmake\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "注意: 包含文件:  "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Estim/Desktop/lin/cmake_code/src/101_first_cmake/nmake/CMakeFiles/CMakeScratch/TryCompile-wom6w4"
      binary: "C:/Users/Estim/Desktop/lin/cmake_code/src/101_first_cmake/nmake/CMakeFiles/CMakeScratch/TryCompile-wom6w4"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Estim/Desktop/lin/cmake_code/src/101_first_cmake/nmake/CMakeFiles/CMakeScratch/TryCompile-wom6w4'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_e57fb\\fast
        	"D:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_e57fb.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_e57fb.dir\\build
        Building C object CMakeFiles/cmTC_e57fb.dir/CMakeCCompilerABI.c.obj
        	"C:\\Program Files\\CMake\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_e57fb.dir\\CMakeCCompilerABI.c.obj.d --working-dir=C:\\Users\\Estim\\Desktop\\lin\\cmake_code\\src\\101_first_cmake\\nmake\\CMakeFiles\\CMakeScratch\\TryCompile-wom6w4 --filter-prefix="注意: 包含文件:  " -- D:\\MICROS~2\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\Estim\\AppData\\Local\\Temp\\nm3CC.tmp
        CMakeCCompilerABI.c
        ?鈷? 鍖呭惈鏂囦欢:  C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCompilerABI.h
        Linking C executable cmTC_e57fb.exe
        	"C:\\Program Files\\CMake\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_e57fb.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\mt.exe --manifests -- D:\\MICROS~2\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_e57fb.dir\\objects1.rsp @C:\\Users\\Estim\\AppData\\Local\\Temp\\nm12E1.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_e57fb.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_e57fb.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_e57fb.dir/manifest.res CMakeFiles\\cmTC_e57fb.dir/manifest.rc
        LINK Pass 1:
        D:\\MICROS~2\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_e57fb.dir\\objects1.rsp /out:cmTC_e57fb.exe /implib:cmTC_e57fb.lib /pdb:C:\\Users\\Estim\\Desktop\\lin\\cmake_code\\src\\101_first_cmake\\nmake\\CMakeFiles\\CMakeScratch\\TryCompile-wom6w4\\cmTC_e57fb.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_e57fb.dir/intermediate.manifest CMakeFiles\\cmTC_e57fb.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_e57fb.dir/intermediate.manifest /out:CMakeFiles\\cmTC_e57fb.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_e57fb.dir/manifest.res CMakeFiles\\cmTC_e57fb.dir/manifest.rc
        FINAL LINK:
        D:\\MICROS~2\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_e57fb.dir\\objects1.rsp /out:cmTC_e57fb.exe /implib:cmTC_e57fb.lib /pdb:C:\\Users\\Estim\\Desktop\\lin\\cmake_code\\src\\101_first_cmake\\nmake\\CMakeFiles\\CMakeScratch\\TryCompile-wom6w4\\cmTC_e57fb.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_e57fb.dir/intermediate.manifest CMakeFiles\\cmTC_e57fb.dir/manifest.res
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/Estim/Desktop/lin/cmake_code/src/101_first_cmake/nmake/CMakeFiles/CMakeScratch/TryCompile-8y2kb6"
      binary: "C:/Users/Estim/Desktop/lin/cmake_code/src/101_first_cmake/nmake/CMakeFiles/CMakeScratch/TryCompile-8y2kb6"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Estim/Desktop/lin/cmake_code/src/101_first_cmake/nmake/CMakeFiles/CMakeScratch/TryCompile-8y2kb6'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_051c5\\fast
        	"D:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_051c5.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_051c5.dir\\build
        Building CXX object CMakeFiles/cmTC_051c5.dir/CMakeCXXCompilerABI.cpp.obj
        	"C:\\Program Files\\CMake\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_051c5.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir=C:\\Users\\Estim\\Desktop\\lin\\cmake_code\\src\\101_first_cmake\\nmake\\CMakeFiles\\CMakeScratch\\TryCompile-8y2kb6 --filter-prefix="注意: 包含文件:  " -- D:\\MICROS~2\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\Estim\\AppData\\Local\\Temp\\nm4450.tmp
        CMakeCXXCompilerABI.cpp
        ?鈷? 鍖呭惈鏂囦欢:  C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCompilerABI.h
        Linking CXX executable cmTC_051c5.exe
        	"C:\\Program Files\\CMake\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_051c5.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\mt.exe --manifests -- D:\\MICROS~2\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_051c5.dir\\objects1.rsp @C:\\Users\\Estim\\AppData\\Local\\Temp\\nm51ED.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_051c5.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_051c5.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_051c5.dir/manifest.res CMakeFiles\\cmTC_051c5.dir/manifest.rc
        LINK Pass 1:
        D:\\MICROS~2\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_051c5.dir\\objects1.rsp /out:cmTC_051c5.exe /implib:cmTC_051c5.lib /pdb:C:\\Users\\Estim\\Desktop\\lin\\cmake_code\\src\\101_first_cmake\\nmake\\CMakeFiles\\CMakeScratch\\TryCompile-8y2kb6\\cmTC_051c5.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_051c5.dir/intermediate.manifest CMakeFiles\\cmTC_051c5.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_051c5.dir/intermediate.manifest /out:CMakeFiles\\cmTC_051c5.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100261~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_051c5.dir/manifest.res CMakeFiles\\cmTC_051c5.dir/manifest.rc
        FINAL LINK:
        D:\\MICROS~2\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_051c5.dir\\objects1.rsp /out:cmTC_051c5.exe /implib:cmTC_051c5.lib /pdb:C:\\Users\\Estim\\Desktop\\lin\\cmake_code\\src\\101_first_cmake\\nmake\\CMakeFiles\\CMakeScratch\\TryCompile-8y2kb6\\cmTC_051c5.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_051c5.dir/intermediate.manifest CMakeFiles\\cmTC_051c5.dir/manifest.res
        
      exitCode: 0
...
